# Generated by Django 4.2.13 on 2024-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
